### ISSUE TITLE
Marketing images

### ISSUE THREAD

**Issue by RommelTJ** [RomzaLabs/KnitCount2#120]
**I'm submitting a ...**

- [x] feature request

Let's compile a list of marketing images that we need. Include sizes and file formats and what they will be used for.

**Comment by RommelTJ** [comment]
Do we want to support tablets?

iOS
- iPhone 6.5" Display (1242 x 2688 pixels (portrait), png, iPhone 11 Pro)
-> Screenshot previewing Projects
-> Screenshot previewing Project Details
-> Screenshot previewing Add a Counter
-> Screenshot previewing Settings

- iPhone 5.5" Display (1242 x 2208 pixels (portrait), png, iPhone 6s Plus)
-> Same 4 screenshot content as 6.5" Display 

Android
- Most popular phone (JPEG or 24-bit PNG (no alpha). Min length for any side: 320px. Max length for any side: 3840px.)
-> Same 4 screenshot content as iOS

- Feature Graphic (1024 w x 500 h, JPG or 24-bit PNG (no alpha))

- Promo Graphic (180 w x 120 h, JPG or 24-bit PNG (no alpha))

**Comment by RommelTJ** [comment]
@leaningtower We have the screenshots for the devices, but are missing the Feature Graphic and Promo Graphic.

**Comment by leaningtower** [comment]
Feature graphic, promo graphic and favicon are on your computer in the sketch project. 

Replace images: 
Change Android picture to this one: ![IMG_1865](https://user-images.githubusercontent.com/15657876/80056731-b8b71f80-84d9-11ea-98b7-ec2ba04725d2.PNG)

Counters: ![IMG_2175](https://user-images.githubusercontent.com/15657876/80056810-f156f900-84d9-11ea-9d87-ec001cfb154c.jpg)

Unlimited projects: https://gph.is/g/aj11ypn 
Fun colors: https://gph.is/g/aQyyQPA

Copy: 
The perfect way to keep track of your stitch counters

Simple, intuitive design and animation for the easiest to use row counter available 

Add as many projects as your heart desires and easily go back to them at any time. Quickly toggle between your Finished Objects and Work In Progress projects. You can even add notes and pictures too!

You can have as many or as little counters per project as you need. Quickly create a standard counter or customize the name and steps per count for more complex projects. 

Fun colors & unique sounds 
8 hand-picked colors and 4 sound packs allow KnitCount to be customized to your unique style. It’s just a little touch of flair without being too distracting.

**Comment by RommelTJ** [comment]
Resolved. Closing.
