### ISSUE TITLE
High Contrast Color and Color Updates

### ISSUE THREAD

**Issue by RommelTJ** [RomzaLabs/KnitCount2#135]
**I'm submitting a ...**

- [x] feature request

There should be at least one high contrast color option, such as black and white. 
Also, this is an opportunity for Liza to review the colors.

**Comment by RommelTJ** [comment]
@leaningtower Here are the current colors: 
```
export default {
  primaryColor: "#1E90FF",
  primaryTextColor: "#FDFDFD",
  primaryBGColor: "#56ABFF",
  clearChillColor: "#1E90FF",
  clearChillTextColor: "#FDFDFD",
  clearChillBGColor: "#56ABFF",
  watermelonColor: "#FF4757",
  watermelonTextColor: "#FDFDFD",
  watermelonBGColor: "#D25579",
  brightGreekColor: "#3742FA",
  brightGreekTextColor: "#FDFDFD",
  brightGreekBGColor: "#3251FB",
  coralColor: "#FF7F50",
  coralTextColor: "#FDFDFD",
  coralBGColor: "#D28273",
  ufoColor: "#2ED573",
  ufoTextColor: "#FDFDFD",
  ufoBGColor: "#2BC68F"
};

```

**Comment by leaningtower** [comment]
Primary and Clear Chill color are the same? Let's keep that color and try
the below:

Orange: FF8F1F
Red: F3323D
Dark Blue: 3D00D6
Green: 06DF68
Pink: EF82BE
Black: 00000

**Comment by leaningtower** [comment]
Orange: FEAA00
Red: FF0000
Dark Blue: 064676
Light Blue: 00A8E2
Green: 00C069
Pink: FF45F7
Black: 333333

**Comment by leaningtower** [comment]
Red: FE6A4C
Orange: FEC34C
Pink: FEA5C3
Purple: E0A5FE

**Comment by leaningtower** [comment]
Purple: D3B1EF

**Comment by leaningtower** [comment]
export default {
  primaryColor: "#00A8E2",
  primaryTextColor: "#FDFDFD",
  primaryBGColor: "#99DCF3",
  clearChillColor: "#00A8E2",
  clearChillTextColor: "#FDFDFD",
  clearChillBGColor: "#99DCF3",
  watermelonColor: "#FE6A4C",
  watermelonTextColor: "#FDFDFD",
  watermelonBGColor: "#FEB4A5",
  brightGreekColor: "#064676",
  brightGreekTextColor: "#FDFDFD",
  brightGreekBGColor: "#9BB5C8",
  coralColor: "#FEC34C",
  coralTextColor: "#FDFDFD",
  coralBGColor: "#FEE1A5",
  ufoColor: "#00C069",
  ufoTextColor: "#FDFDFD",
  ufoBGColor: "#7FDFB4",
  pinkColor: "#FEA5C3",
  pinkTextColor: "#FDFDFD",
  pinkBGColor: "#FED2E1",
  blackColor: "#333333",
  blackTextColor: "#FDFDFD",
  blackBGColor: "#ADADAD",
  lavenderColor: "#D3B1EF",
  lavenderTextColor: "#FDFDFD",
  lavenderBGColor: "#E9D8F7"
};



const supportedColors = [
  Colors.clearChillColor,
  Colors.watermelonColor,
  Colors.brightGreekColor,
  Colors.coralColor,
  Colors.blackColor,
  Colors.pinkColor,
  Colors.ufoColor,
  Colors.lavenderColor
];

**Comment by leaningtower** [comment]
export default {
  primaryColor: "#00A8E2",
  primaryTextColor: "#FDFDFD",
  primaryBGColor: "#66CAED",
  clearChillColor: "#00A8E2",
  clearChillTextColor: "#FDFDFD",
  clearChillBGColor: "#66CAED",
  watermelonColor: "#FE6A4C",
  watermelonTextColor: "#FDFDFD",
  watermelonBGColor: "#FE9681",
  brightGreekColor: "#064676",
  brightGreekTextColor: "#FDFDFD",
  brightGreekBGColor: "#6990AC",
  coralColor: "#FEC34C",
  coralTextColor: "#FDFDFD",
  coralBGColor: "#FEDB93",
  ufoColor: "#00C069",
  ufoTextColor: "#FDFDFD",
  ufoBGColor: "#66D9A5",
  pinkColor: "#FEA5C3",
  pinkTextColor: "#FDFDFD",
  pinkBGColor: "#FEC9DB",
  blackColor: "#333333",
  blackTextColor: "#FDFDFD",
  blackBGColor: "#848484",
  lavenderColor: "#D3B1EF",
  lavenderTextColor: "#FDFDFD",
  lavenderBGColor: "#E4D0F5"
};

**Comment by RommelTJ** [comment]
Resolved in https://github.com/RomzaLabs/KnitCount2/pull/146
