### ISSUE TITLE
Android Audio Focus not acquired

### ISSUE THREAD

**Issue by RommelTJ** [RomzaLabs/KnitCount2#162]
**I'm submitting a ...**

- [x] bug report

Android OS ultimately controls audio focus. You can lose audio focus if, for example, another app takes control or you get a phone call. Audio in KnitCount is very optional, so let's just capture the error and silence it so it doesn't record in Sentry.

Error: 
expo.modules.av.AudioFocusNotAcquiredException: Audio focus could not be acquired from the OS at this time.

**Comment by RommelTJ** [comment]
Resolved in https://github.com/RomzaLabs/KnitCount2/pull/166

**Comment by XantreGodlike** [comment]
It started to happen again: `Error: expo.modules.av.AudioFocusNotAcquiredException: Audio focus could not be acquired from the OS at this time.`
<img width="1090" alt="image" src="https://github.com/RomzaLabs/KnitCount2/assets/57757211/38c72d73-734f-4341-b0a6-9c7e504f00f0">
