### ISSUE TITLE
Analytics / Crash reporting 

### ISSUE THREAD

**Issue by RommelTJ** [RomzaLabs/KnitCount2#87]
**I'm submitting a ...**

- [x] feature request

Analytics and Crash Reporting

**Comment by RommelTJ** [comment]
https://invertase.io/blog/firebase-crashlytics-for-react-native

**Comment by sdufel** [comment]
Can you add some more details to this?

**Comment by RommelTJ** [comment]
@sdufel Dammit

**Comment by RommelTJ** [comment]
> If you'd like to use Firebase in the Expo client with the managed workflow, we'd recommend using the Firebase JS SDK. It supports Firebase's Realtime Database, Firestore, Storage and Authentication (except phone auth). If you'd like access to the full suite of native firebase tools, we recommend using the bare workflow and react-native-firebase, because we cannot support this in the Expo client currently.

https://blog.expo.io/using-firebase-in-expo-e13844061832

Never mind, fuck that shit. I'll use something else. Sentry and Bugsnag look promising.

**Comment by RommelTJ** [comment]
Let's go with Sentry. They have better documentation, more integrations, and looks pretty easy to use and maintained.
https://sentry.io/

**Comment by RommelTJ** [comment]
Resolved in https://github.com/RomzaLabs/KnitCount2/pull/116
